Adding US egg production data for 2023-04-11
rfordatascience/tidytuesday pull request #543
Opened 2023-04-08 21:49 UTC by tracykteal

Dataset from [US Egg Production Dataset](https://thehumaneleague.org/article/E008R01-us-egg-production-data) by @samaramendez.

2023-04-08 22:04 UTC, jonthegeek requested changes
Just a couple variable names to tweak in the data load, I'll commit these suggestions then merge!

2023-04-08 22:04 UTC, jonthegeek commented on data/2023/2023-04-11/readme.md
> +transitions <- readr::read_csv('https://raw.githubusercontent.com/rfordatascience/tidytuesday/master/data/2023/2023-04-11/egg-production.csv')
```suggestion
eggproduction  <- readr::read_csv('https://raw.githubusercontent.com/rfordatascience/tidytuesday/master/data/2023/2023-04-11/egg-production.csv')
```

2023-04-08 22:04 UTC, jonthegeek commented on data/2023/2023-04-11/readme.md
> +timezones <- readr::read_csv('https://raw.githubusercontent.com/rfordatascience/tidytuesday/master/data/2023/2023-04-11/cage-free-percentages.csv')
```suggestion
cagefreepercentages <- readr::read_csv('https://raw.githubusercontent.com/rfordatascience/tidytuesday/master/data/2023/2023-04-11/cage-free-percentages.csv')
```

2023-04-08 22:05 UTC, jonthegeek approved these changes
Ok, fixed!

2023-04-08 22:05 UTC, merged

2023-04-09 16:56 UTC, samaramendez commented
Thanks for using my dataset! I've just updated the files in [the repository ](https://osf.io/z2gxn/) with the most recent data, if you'd like to include 2023 data.

2023-04-10 16:20 UTC, tracykteal commented
That's great, thank you @samaramendez! We keep the datasets small for TidyTuesday, but I'll update the README to show that the most recent data is available in the repo.