adding 2023-07-11 data
rfordatascience/tidytuesday pull request #580
Opened 2023-07-09 16:16 UTC by tracykteal

2023-07-09 16:20 UTC, tracykteal commented
Closes https://github.com/rfordatascience/tidytuesday/issues/462

Thanks @BB1464

2023-07-10 00:53 UTC, jonthegeek requested changes
A couple typos that I'll commit, then I'll merge the whole thing 🎉

2023-07-10 00:53 UTC, jonthegeek commented on data/2023/2023-07-11/post_vars.json
> +  "pic2_alt": "Global map showing temparture differences in 2023 compared with the time period 1951-1980. Most areas of the map indicate that temperatures are 1 to 2 degrees warmer. Areas of northern
```suggestion
  "pic2_alt": "Global map showing temperature differences in 2023 compared with the time period 1951-1980. Most areas of the map indicate that temperatures are 1 to 2 degrees warmer. Areas of northern Canada, northern Russia and Antarctica are up to 6.5 degees warmer. Some areas over oceans are the same or slightly cooler. An estimate for the global mean of the calculated field is 0.94 degrees."
```

2023-07-10 00:53 UTC, jonthegeek commented on data/2023/2023-07-11/readme.md
> +The data this week comes from the [NASA GISS Surface Temperature Analysis (GISTEMP v4)](https://data.giss.nasa.gov/gistemp/). This dataset are tables of global and hemispheric monthly means and zonal
```suggestion
The data this week comes from the [NASA GISS Surface Temperature Analysis (GISTEMP v4)](https://data.giss.nasa.gov/gistemp/). This datasets are tables of global and hemispheric monthly means and zonal annual means. They combine land-surface, air and sea-surface water temperature anomalies (Land-Ocean Temperature Index, L-OTI). The values in the tables are deviations from the corresponding 1951-1980 means.
```

2023-07-10 00:53 UTC, jonthegeek commented on data/2023/2023-07-11/readme.md
> +global_temps <- tuesdata$`global_temps`
```suggestion
global_temps <- tuesdata$global_temps
```

2023-07-10 00:53 UTC, jonthegeek commented on data/2023/2023-07-11/readme.md
> +nh_temps <- tuesdata$`nh_temps`
```suggestion
nh_temps <- tuesdata$nh_temps
```

2023-07-10 00:53 UTC, jonthegeek commented on data/2023/2023-07-11/readme.md
> +sh_temps <- tuesdata$`sh_temps`
```suggestion
sh_temps <- tuesdata$sh_temps
```

2023-07-10 00:53 UTC, jonthegeek commented on data/2023/2023-07-11/readme.md
> +zonann_temps <- tuesdata$`zonann_temps`
```suggestion
zonann_temps <- tuesdata$zonann_temps
```

2023-07-10 00:55 UTC, merged