created content for pull request for TT - Fragrance Dataset
rfordatascience/tidytuesday pull request #776
Opened 2024-11-25 07:18 UTC by nicolasfoss

Thank you for your submission! Please leave this text as-is when you submit, and then check the checklist.

Usability:

- [✔️] This dataset has not already been used in TidyTuesday.
- [✔️] The dataset is less than 20MB when saved as a tidy CSV.
- [✔️] I can imagine at least one data visualization related to this dataset.

Preparation:

- [✔️] `cleaning.R` has code to download and clean the dataset, resulting in descriptively-named data.frames.
- [✔️] I ran `saving.R` to create `csv`s and `md` data dictionaries for each of my data.frames.
- [✔️] I filled in descriptions for each variable in each of the `{dataset}.md` files.
- [✔️] I edited the `intro.md` file to introduce my dataset.
- [✔️] I included at least one image for my dataset as a `png` file.
- [✔️] I completed the information in `meta.yaml`, including descriptive alt text for each image.
- [✔️] I provided information in `meta.yaml` about how to credit me, and deleted any parts of that block that I do not want you to use.

2024-11-25 13:29 UTC, jonthegeek commented
@nicolasfoss Thank you so much for the submission! I'll review it later today!

FYI, on GitHub you can use an empty pair of square brackets in a bulleted list (like this `- [ ]` for an interactive checkbox, or you can fill it in with an x like `- [x]` for a checked box. I should probably spell that out in the template! Then GitHub tracks the items as "to-do" for that particular issue or PR. Eg:

- [ ] Describe how checkboxes work.
- [ ] Write a ticket to clean up the PR instructions.

2024-11-25 13:49 UTC, nicolasfoss commented
I wondered about that! 

I will do that for the Dr. Nick dataset. I will probably submit that next week sometime. 

Thanks for all the instructions. It made everything easy to use. I use GitHub desktop so that's the route I went but it's basically the same thing.

2024-11-25 15:12 UTC, nicolasfoss commented
@jonthegeek I fixed the checkbook for good measure. 

Have a great day!

2024-11-25 15:47 UTC, jonthegeek commented
> @jonthegeek I fixed the checkboxes for good measure.

Isn't it more satisfying that way? 😁 

Thanks for the submission(s)! I'm trying to "finish" dataset curation for the year within the next few days, and your Dr. Nick dataset will leave just 1 more (besides the one I'm working on)! 🎉

2024-11-26 14:51 UTC, jonthegeek requested changes
Just a few tweaks. I'll apply the changes myself, then assign this to a week. Thanks again!

2024-11-26 14:51 UTC, jonthegeek commented on data/curated/parfumo_fragrance/cleaning.R
> +library(here)
```suggestion
library(naniar)
```

2024-11-26 14:51 UTC, jonthegeek commented on data/curated/parfumo_fragrance/intro.md
> +This week, we're diving into the fascinating world of fragrances with a dataset sourced from [Parfumo](https://www.parfumo.com/), a vibrant community of perfume enthusiasts.  [Olga G.](https://www.ka
```suggestion
This week we're diving into the fascinating world of fragrances with a dataset sourced from [Parfumo](https://www.parfumo.com/), a vibrant community of perfume enthusiasts.  [Olga G.](https://www.kaggle.com/olgagmiufana1) webscraped these data from the various fragrance sections on the Parfumo website. Here is a description from the author:
```

2024-11-26 14:51 UTC, jonthegeek commented on data/curated/parfumo_fragrance/intro.md
> +Thank you to [Nicolas Foss](www.linkedin.com/in/nicolas-foss) this week's dataset.
```suggestion
```
You'll automatically be credited with a link to your GitHub profile.

2024-11-26 14:52 UTC, jonthegeek commented
/assign parfumo_fragrance 2024-12-10

2024-11-26 15:01 UTC, jonthegeek commented
Oh, not quite! Please don't delete sections of the meta.yaml file! I'm adding an article (which really means "anything that talks about the data", so https://www.parfumo.com/Perfumes works), and making sure nothing else is missing.

2024-11-26 15:04 UTC, jonthegeek commented
/assign parfumo_fragrance 2024-12-10

2024-11-26 15:11 UTC, jonthegeek approved these changes
This will do it. Thanks!

2024-11-26 15:11 UTC, jonthegeek commented on README.md
> +| 50 | `2024-12-10` | [The Scent of Data - Exploring the Parfumo Fragrance Dataset](data/2024/2024-12-10/readme.md) | [Parfumo Fragrance Dataset ](https://www.kaggle.com/datasets/olgagmiufana1/parfum
```suggestion
| 50 | `2024-12-10` | [The Scent of Data - Exploring the Parfumo Fragrance Dataset](data/2024/2024-12-10/readme.md) | [Parfumo Fragrance Dataset](https://www.kaggle.com/datasets/olgagmiufana1/parfumo-fragrance-dataset) | [Perfumes at parfumo](https://www.parfumo.com/Perfumes) | 
```

2024-11-26 15:11 UTC, jonthegeek commented on data/2024/2024-12-10/meta.yaml
> +  title: "Parfumo Fragrance Dataset "
```suggestion
  title: "Parfumo Fragrance Dataset"
```

2024-11-26 15:11 UTC, jonthegeek commented on data/2024/readme.md
> +| 50 | `2024-12-10` | [The Scent of Data - Exploring the Parfumo Fragrance Dataset](2024-12-10/readme.md) | [Parfumo Fragrance Dataset ](https://www.kaggle.com/datasets/olgagmiufana1/parfumo-fragranc
```suggestion
| 50 | `2024-12-10` | [The Scent of Data - Exploring the Parfumo Fragrance Dataset](2024-12-10/readme.md) | [Parfumo Fragrance Dataset](https://www.kaggle.com/datasets/olgagmiufana1/parfumo-fragrance-dataset) | [Perfumes at parfumo](https://www.parfumo.com/Perfumes) |  
```

2024-11-26 15:11 UTC, merged