pokemon!
rfordatascience/tidytuesday pull request #789
Opened 2024-12-24 17:02 UTC by frankiethull

Thank you for your submission! Please leave this text as-is when you submit, and then check the checklist.

Usability:

- [x] This dataset has not already been used in TidyTuesday.
- [x] The dataset is less than 20MB when saved as a tidy CSV.
- [x ] I can imagine at least one data visualization related to this dataset.

Preparation:

- [x] `cleaning.R` has code to download and clean the dataset, resulting in descriptively-named data.frames.
- [x] I ran `saving.R` to create `csv`s and `md` data dictionaries for each of my data.frames.
- [x] I filled in descriptions for each variable in each of the `{dataset}.md` files.
- [x] I edited the `intro.md` file to introduce my dataset.
- [x] I included at least one image for my dataset as a `png` file.
- [x] I completed the information in `meta.yaml`, including descriptive alt text for each image.
- [x] I provided information in `meta.yaml` about how to credit me, and deleted any parts of that block that I do not want you to use.

2025-02-12 12:39 UTC, jonthegeek requested changes
Just a few tweaks needed overall, but the main thing is that your submission directory is ephemeral; we only keep the pieces designated in the instructions. If you want to use an article that you wrote for the article link, you need to publish it on your own GitHub account. It's also fine to link to virtually anything about Pokemon for the article.

Thanks for the submission!

2025-02-12 12:39 UTC, jonthegeek commented on data/curated/pokemon/intro.md
> +
```suggestion
```
This part is a description for you, and shouldn't appear in your intro.

2025-02-12 12:39 UTC, jonthegeek commented on data/curated/pokemon/intro.md
> +> A dataset of Pokemon information
```suggestion
This week we are exploring Pokemon! This dataset is sourced from {pokemon} ([CRAN](https://cran.r-project.org/package=pokemon) | [github](https://github.com/williamorim/pokemon)), an R package which provides Pokemon information in both English and Brazilian Portuguese.

> This package provides a dataset of Pokemon information in both English and Brazilian Portuguese. The dataset contains 949 rows and 22 columns, including information such as the Pokemon’s name, ID, height, weight, stats, type, and more.
```

2025-02-12 12:39 UTC, jonthegeek commented on data/curated/pokemon/cleaning.R
> +
```suggestion
```

2025-02-12 12:39 UTC, jonthegeek commented on data/curated/pokemon/intro.md
> +QUESTION?
```suggestion
```
This is intended as a prompt to you, to add one or more questions to the end of the introduction.

2025-02-12 12:39 UTC, jonthegeek commented on data/curated/pokemon/meta.yaml
> +  url: github.com/frankiethull/tidytuesday/tree/pokemon/data/curated/pokemon/article.md
The link needs to be to an existing thing on the internet. This directory is deleted during the acceptance process, so it can't "live" here. Either publish it on your own GitHub, or provide a link to anything about Pokemon, ideally showing some use of data, but something like the source of the data or a wikipedia article about Pokemon or anything else would work.

2025-02-12 12:39 UTC, jonthegeek commented on data/curated/pokemon/meta.yaml
> +  title: pokemon
```suggestion
  title: pokemon R package
```

2025-02-12 12:39 UTC, jonthegeek commented on data/curated/pokemon/meta.yaml
> +    Image shows faceted scatterplots of pokemon dataset. x = attack; y = defense; facet = pokemon type; color = primary pokemon color;
Describe the image in a way that serves to replace the image when the image isn't available. What does the plot show? Are there trends? Is there one type that stands out as more defense-focused, or another that's more attack-focused? Or maybe pointing out the type with the strongest attack and the type with the strongest defense.

2025-02-12 12:39 UTC, jonthegeek commented on data/curated/pokemon/meta.yaml
> +  bluesky: https://bsky.app/profile/frankiethull
```suggestion
  bluesky: https://bsky.app/profile/frankiethull.bsky.social
```

2025-03-05 23:09 UTC, frankiethull commented on data/curated/pokemon/meta.yaml
> +  url: github.com/frankiethull/tidytuesday/tree/pokemon/data/curated/pokemon/article.md
I was originally thinking the article would live on my fork. But I'll go with the second idea, providing a link to anything about Pokemon. Will look around for one that uses the underlying data (if possible).

2025-03-25 22:22 UTC, frankiethull commented on data/curated/pokemon/meta.yaml
> +  url: github.com/frankiethull/tidytuesday/tree/pokemon/data/curated/pokemon/article.md
I was unable to find an article that references the library directly in my perusing. I changed this to a different internet article that uses R for EDA on a different pokemon dataset.

2025-03-25 22:23 UTC, frankiethull commented on data/curated/pokemon/meta.yaml
> +    Image shows faceted scatterplots of pokemon dataset. x = attack; y = defense; facet = pokemon type; color = primary pokemon color;
@jonthegeek - I updated the chart description a moment ago. let me know what you think.

2025-03-26 11:29 UTC, jonthegeek reviewed
I made some small tweaks, but this looks great! There will be a couple more messages when I run the process and then review & accept the final result.

2025-03-26 11:32 UTC, jonthegeek commented
/assign 2025-04-01 pokemon

2025-03-26 11:38 UTC, jonthegeek approved these changes
Thanks again!

2025-03-26 11:38 UTC, merged

2025-03-26 22:21 UTC, frankiethull commented
thank you so much! Apologies on taking so long after my initial PR. 

But again, thank you for making me strive for better alt text, data documentation, always learning from these little PR, appreciate you helping me along the way!